import type {Metadata} from "next";
import MenuComponent from "@/components/MenuComponent/MenuComponent";
import InformationComponent from "@/components/InformationComponent/InformationComponent";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


export default async function Item({ params }: { params: Promise<{ item: string }> }) {
    const { item } = await params;
    metadata.title = `${item}`
    return (
        <div>
            <MenuComponent showMenu={false}/>
            <InformationComponent params={item}/>
        </div>
    );
}